insert into place (name, type_id, location_id) values ('Sandakan', 2, 73);
insert into place (name, type_id, location_id) values ('Pretoria', 2, 44);
insert into place (name, type_id, location_id) values ('Changyanbao', 2, 100);
insert into place (name, type_id, location_id) values ('Janowiec', 2, 41);
insert into place (name, type_id, location_id) values ('Denver', 4, 69);
insert into place (name, type_id, location_id) values ('Guaynabo', 1, 105);
insert into place (name, type_id, location_id) values ('Nowy Tomyśl', 2, 50);
insert into place (name, type_id, location_id) values ('Villa Verde', 1, 45);
insert into place (name, type_id, location_id) values ('Toupi', 4, 50);
insert into place (name, type_id, location_id) values ('Merapit', 3, 107);
insert into place (name, type_id, location_id) values ('Shizong', 1, 46);
insert into place (name, type_id, location_id) values ('Longtan', 4, 123);
insert into place (name, type_id, location_id) values ('Huangzhawan', 2, 90);
insert into place (name, type_id, location_id) values ('Muzhijie', 3, 123);
insert into place (name, type_id, location_id) values ('Xinkai', 3, 49);
insert into place (name, type_id, location_id) values ('Dongmafang', 3, 132);
insert into place (name, type_id, location_id) values ('San Juan', 2, 50);
insert into place (name, type_id, location_id) values ('Khān Neshīn', 2, 42);
insert into place (name, type_id, location_id) values ('Kingsport', 1, 142);
insert into place (name, type_id, location_id) values ('Tampa', 1, 130);
insert into place (name, type_id, location_id) values ('Bukovec', 3, 129);
insert into place (name, type_id, location_id) values ('Bearna', 3, 63);
insert into place (name, type_id, location_id) values ('Los Angeles', 1, 108);
insert into place (name, type_id, location_id) values ('Zargarān', 1, 96);
insert into place (name, type_id, location_id) values ('Pazarić', 2, 41);
insert into place (name, type_id, location_id) values ('Cihe', 4, 95);
insert into place (name, type_id, location_id) values ('Igoumenítsa', 3, 73);
insert into place (name, type_id, location_id) values ('Herne', 1, 41);
insert into place (name, type_id, location_id) values ('Viljakkala', 2, 110);
insert into place (name, type_id, location_id) values ('Jangas', 2, 65);
insert into place (name, type_id, location_id) values ('Ungca', 2, 108);
insert into place (name, type_id, location_id) values ('Göteborg', 3, 128);
insert into place (name, type_id, location_id) values ('Kīsh', 1, 144);
insert into place (name, type_id, location_id) values ('San Diego', 1, 124);
insert into place (name, type_id, location_id) values ('Altavista', 4, 41);
insert into place (name, type_id, location_id) values ('Wufeng', 1, 144);
insert into place (name, type_id, location_id) values ('Omuthiya', 4, 50);
insert into place (name, type_id, location_id) values ('Pangawaren', 1, 144);
insert into place (name, type_id, location_id) values ('Farsta', 2, 103);
insert into place (name, type_id, location_id) values ('Hernández', 4, 103);
insert into place (name, type_id, location_id) values ('Vilela', 4, 98);
insert into place (name, type_id, location_id) values ('Alvide', 3, 90);
insert into place (name, type_id, location_id) values ('Huntsville', 2, 55);
insert into place (name, type_id, location_id) values ('Al ‘Udayn', 3, 142);
insert into place (name, type_id, location_id) values ('Wosai', 1, 109);
insert into place (name, type_id, location_id) values ('Shypyntsi', 2, 133);
insert into place (name, type_id, location_id) values ('Silvares', 2, 132);
insert into place (name, type_id, location_id) values ('Les Abymes', 1, 129);
insert into place (name, type_id, location_id) values ('San Buenaventura', 4, 126);
insert into place (name, type_id, location_id) values ('Qal‘ah-ye Kuhnah', 4, 133);
insert into place (name, type_id, location_id) values ('Sanzhang', 3, 47);
insert into place (name, type_id, location_id) values ('Kálamos', 2, 70);
insert into place (name, type_id, location_id) values ('Bairan', 2, 136);
insert into place (name, type_id, location_id) values ('Itapuí', 2, 78);
insert into place (name, type_id, location_id) values ('Cibaregbeg', 3, 144);
insert into place (name, type_id, location_id) values ('Shimen', 2, 144);
insert into place (name, type_id, location_id) values ('Caihua', 3, 129);
insert into place (name, type_id, location_id) values ('Virje', 2, 144);
insert into place (name, type_id, location_id) values ('Motema', 2, 83);
insert into place (name, type_id, location_id) values ('Daminggong', 1, 110);
insert into place (name, type_id, location_id) values ('Jingzhou', 4, 44);
insert into place (name, type_id, location_id) values ('Nāḩiyat Baḩār', 4, 90);
insert into place (name, type_id, location_id) values ('Jincang', 1, 44);
insert into place (name, type_id, location_id) values ('Bidikotak', 4, 63);
insert into place (name, type_id, location_id) values ('Muromtsevo', 1, 126);
insert into place (name, type_id, location_id) values ('Grebnevo', 1, 84);
insert into place (name, type_id, location_id) values ('Smarhon’', 2, 79);
insert into place (name, type_id, location_id) values ('Cepões', 4, 138);
insert into place (name, type_id, location_id) values ('Santa Lucia', 2, 144);
insert into place (name, type_id, location_id) values ('Aldeia da Mata', 3, 123);
insert into place (name, type_id, location_id) values ('Bochum', 2, 130);
insert into place (name, type_id, location_id) values ('Malaya Dubna', 3, 76);
insert into place (name, type_id, location_id) values ('Pospelikha', 3, 64);
insert into place (name, type_id, location_id) values ('Bagakay', 3, 55);
insert into place (name, type_id, location_id) values ('Mijiang', 2, 130);
insert into place (name, type_id, location_id) values ('Balakliya', 4, 138);
insert into place (name, type_id, location_id) values ('Qagan Obo', 3, 105);
insert into place (name, type_id, location_id) values ('Duobaoshan', 2, 124);
insert into place (name, type_id, location_id) values ('Chengyang', 1, 70);
insert into place (name, type_id, location_id) values ('Simi Valley', 3, 139);
insert into place (name, type_id, location_id) values ('Sukomulyo', 3, 86);
insert into place (name, type_id, location_id) values ('Staraya Russa', 2, 40);
insert into place (name, type_id, location_id) values ('Cullinan', 1, 108);
insert into place (name, type_id, location_id) values ('Poddębice', 4, 120);
insert into place (name, type_id, location_id) values ('Oberá', 4, 50);
insert into place (name, type_id, location_id) values ('Shchukino', 1, 82);
insert into place (name, type_id, location_id) values ('Słubice', 3, 108);
insert into place (name, type_id, location_id) values ('Pontivy', 3, 53);
insert into place (name, type_id, location_id) values ('Barranco de Loba', 2, 138);
insert into place (name, type_id, location_id) values ('Wotho', 4, 143);
insert into place (name, type_id, location_id) values ('Gubengairlangga', 3, 131);
insert into place (name, type_id, location_id) values ('Niort', 3, 40);
insert into place (name, type_id, location_id) values ('Pantaihambawang', 1, 82);
insert into place (name, type_id, location_id) values ('Naha-shi', 1, 106);
insert into place (name, type_id, location_id) values ('Nueva Guadalupe', 4, 96);
insert into place (name, type_id, location_id) values ('Altay', 3, 62);
insert into place (name, type_id, location_id) values ('Detroit', 1, 95);
insert into place (name, type_id, location_id) values ('Cholpon-Ata', 1, 60);
insert into place (name, type_id, location_id) values ('Pathum Thani', 2, 42);
insert into place (name, type_id, location_id) values ('Oneop', 1, 70);
insert into place (name, type_id, location_id) values ('Yefremov', 1, 110);
insert into place (name, type_id, location_id) values ('Betong', 4, 56);
insert into place (name, type_id, location_id) values ('Tamanar', 1, 77);
insert into place (name, type_id, location_id) values ('Mauren', 3, 108);
insert into place (name, type_id, location_id) values ('Padamulya', 4, 136);
insert into place (name, type_id, location_id) values ('Bilovods''k', 1, 125);
insert into place (name, type_id, location_id) values ('Mesiméri', 2, 41);
insert into place (name, type_id, location_id) values ('Żyrardów', 2, 48);
insert into place (name, type_id, location_id) values ('Famaillá', 1, 97);
insert into place (name, type_id, location_id) values ('Lincoln', 1, 66);
insert into place (name, type_id, location_id) values ('Angochi', 3, 89);
insert into place (name, type_id, location_id) values ('Drayton Valley', 1, 53);
insert into place (name, type_id, location_id) values ('Ağdam', 1, 72);
insert into place (name, type_id, location_id) values ('Chame', 3, 144);
insert into place (name, type_id, location_id) values ('Burgkirchen', 4, 82);
insert into place (name, type_id, location_id) values ('Miaoqian', 1, 50);
insert into place (name, type_id, location_id) values ('Qianwei', 4, 121);
insert into place (name, type_id, location_id) values ('Lagayan', 4, 66);
insert into place (name, type_id, location_id) values ('Novopskov', 1, 58);
insert into place (name, type_id, location_id) values ('Zelenograd', 2, 114);
insert into place (name, type_id, location_id) values ('Lodwar', 3, 106);
insert into place (name, type_id, location_id) values ('Palaióchora', 1, 77);
insert into place (name, type_id, location_id) values ('Rožmitál pod Třemšínem', 1, 50);
insert into place (name, type_id, location_id) values ('Vihāri', 3, 46);
insert into place (name, type_id, location_id) values ('Mimbaan Timur', 1, 138);
insert into place (name, type_id, location_id) values ('Tonantins', 3, 127);
insert into place (name, type_id, location_id) values ('Nevinnomyssk', 3, 80);
insert into place (name, type_id, location_id) values ('Salavat', 4, 107);
insert into place (name, type_id, location_id) values ('Santa Rosa', 2, 55);
insert into place (name, type_id, location_id) values ('Ban Huai Thalaeng', 4, 96);
insert into place (name, type_id, location_id) values ('Huangliang', 3, 41);
insert into place (name, type_id, location_id) values ('Phoenix', 2, 125);
insert into place (name, type_id, location_id) values ('Huasahuasi', 4, 109);
insert into place (name, type_id, location_id) values ('Samajie Ewenkeminzu', 1, 96);
insert into place (name, type_id, location_id) values ('Cieurih Satu', 2, 64);
insert into place (name, type_id, location_id) values ('Guyancourt', 2, 114);
insert into place (name, type_id, location_id) values ('Lingqiao', 4, 103);
insert into place (name, type_id, location_id) values ('Cañuelas', 2, 123);
insert into place (name, type_id, location_id) values ('Reguengos de Monsaraz', 3, 74);
insert into place (name, type_id, location_id) values ('Tugusirna', 1, 76);
insert into place (name, type_id, location_id) values ('Kafr Mandā', 4, 127);
insert into place (name, type_id, location_id) values ('Purwokerto', 1, 50);
insert into place (name, type_id, location_id) values ('Ormstown', 3, 96);
insert into place (name, type_id, location_id) values ('Huanuni', 1, 114);
insert into place (name, type_id, location_id) values ('Bokkos', 4, 103);
insert into place (name, type_id, location_id) values ('Debrzno', 2, 69);
insert into place (name, type_id, location_id) values ('Alcanhões', 1, 130);
insert into place (name, type_id, location_id) values ('Mariestad', 2, 81);
insert into place (name, type_id, location_id) values ('Tierimu', 2, 97);
insert into place (name, type_id, location_id) values ('Krajan Keboromo', 4, 132);
insert into place (name, type_id, location_id) values ('Nankou', 1, 67);
insert into place (name, type_id, location_id) values ('Chuanshan', 4, 123);
insert into place (name, type_id, location_id) values ('Charikar', 2, 111);
insert into place (name, type_id, location_id) values ('Yuhuazhai', 1, 144);
insert into place (name, type_id, location_id) values ('Trenggulunan', 3, 132);
insert into place (name, type_id, location_id) values ('Tvarožná', 4, 41);
insert into place (name, type_id, location_id) values ('Toulouse', 2, 140);
insert into place (name, type_id, location_id) values ('Elbasan', 3, 117);
insert into place (name, type_id, location_id) values ('Nerópolis', 4, 86);
insert into place (name, type_id, location_id) values ('Ngudu', 3, 100);
insert into place (name, type_id, location_id) values ('Shuigou', 3, 56);
insert into place (name, type_id, location_id) values ('Sanli', 1, 59);
insert into place (name, type_id, location_id) values ('Panambi', 1, 96);
insert into place (name, type_id, location_id) values ('Ghurayd Gharamē', 1, 92);
insert into place (name, type_id, location_id) values ('Carazinho', 3, 101);
insert into place (name, type_id, location_id) values ('Quanzhou', 3, 136);
insert into place (name, type_id, location_id) values ('Velyka Mykhaylivka', 3, 78);
insert into place (name, type_id, location_id) values ('Mrzeżyno', 2, 140);
insert into place (name, type_id, location_id) values ('Ningyuan', 3, 42);
insert into place (name, type_id, location_id) values ('Lingquan', 3, 45);
insert into place (name, type_id, location_id) values ('Santa Luzia', 2, 128);
insert into place (name, type_id, location_id) values ('Zhongxinqiao', 1, 86);
insert into place (name, type_id, location_id) values ('Okocim', 3, 72);
insert into place (name, type_id, location_id) values ('Beigang', 4, 66);
insert into place (name, type_id, location_id) values ('Biryulëvo Zapadnoye', 3, 108);
insert into place (name, type_id, location_id) values ('Hanlin', 3, 129);
insert into place (name, type_id, location_id) values ('Langford', 3, 119);
insert into place (name, type_id, location_id) values ('Grębków', 2, 111);
insert into place (name, type_id, location_id) values ('Wan’an', 1, 69);
insert into place (name, type_id, location_id) values ('Mamonit', 1, 61);
insert into place (name, type_id, location_id) values ('Sann', 2, 115);
insert into place (name, type_id, location_id) values ('Cabeçudos', 2, 59);
insert into place (name, type_id, location_id) values ('Rancamaya', 1, 86);
insert into place (name, type_id, location_id) values ('Shangrao', 1, 41);
insert into place (name, type_id, location_id) values ('Mekarsari', 4, 41);
insert into place (name, type_id, location_id) values ('Villa Bisonó', 2, 41);
insert into place (name, type_id, location_id) values ('Lewo', 2, 117);
insert into place (name, type_id, location_id) values ('San Miguel', 2, 75);
insert into place (name, type_id, location_id) values ('Selorejo', 4, 41);
insert into place (name, type_id, location_id) values ('Kofelē', 4, 139);
insert into place (name, type_id, location_id) values ('Zhengyu', 4, 80);
insert into place (name, type_id, location_id) values ('Wangchuanchang', 1, 49);
insert into place (name, type_id, location_id) values ('Billa', 3, 112);
insert into place (name, type_id, location_id) values ('Houmen', 1, 146);
insert into place (name, type_id, location_id) values ('Zhanjia', 2, 90);
insert into place (name, type_id, location_id) values ('Cinangsih Satu', 3, 85);
insert into place (name, type_id, location_id) values ('Chernomorets', 3, 131);
insert into place (name, type_id, location_id) values ('Cete', 1, 57);
insert into place (name, type_id, location_id) values ('Songjiang', 3, 62);
insert into place (name, type_id, location_id) values ('Täby', 4, 109);
insert into place (name, type_id, location_id) values ('Tagakpan', 2, 108);
insert into place (name, type_id, location_id) values ('Somita', 2, 100);
insert into place (name, type_id, location_id) values ('Xiaocun', 3, 125);
insert into place (name, type_id, location_id) values ('Pangansalan', 3, 60);
insert into place (name, type_id, location_id) values ('Quxi', 4, 144);
insert into place (name, type_id, location_id) values ('Lysekil', 4, 100);
insert into place (name, type_id, location_id) values ('Shen’ao', 2, 126);
insert into place (name, type_id, location_id) values ('Korydallós', 4, 48);
insert into place (name, type_id, location_id) values ('Donghai', 2, 69);
insert into place (name, type_id, location_id) values ('Pirok', 4, 85);
insert into place (name, type_id, location_id) values ('Glogovac', 3, 115);
insert into place (name, type_id, location_id) values ('Pandi', 4, 122);
insert into place (name, type_id, location_id) values ('Xinshi', 3, 44);
insert into place (name, type_id, location_id) values ('Eucaliptus', 3, 62);
insert into place (name, type_id, location_id) values ('Malysheva', 1, 51);
insert into place (name, type_id, location_id) values ('Wang Muang', 3, 70);
insert into place (name, type_id, location_id) values ('Cinyumput', 4, 113);
insert into place (name, type_id, location_id) values ('Ciharalang', 4, 95);
insert into place (name, type_id, location_id) values ('Karangturi', 1, 78);
insert into place (name, type_id, location_id) values ('Acarigua', 4, 74);
insert into place (name, type_id, location_id) values ('North Saanich', 1, 78);
insert into place (name, type_id, location_id) values ('Vlorë', 4, 103);
insert into place (name, type_id, location_id) values ('Tieling', 3, 138);
insert into place (name, type_id, location_id) values ('Zwolle', 1, 40);
insert into place (name, type_id, location_id) values ('Tarariras', 4, 117);
insert into place (name, type_id, location_id) values ('Calachuchi', 2, 144);
insert into place (name, type_id, location_id) values ('Houzhai', 4, 100);
insert into place (name, type_id, location_id) values ('Markham', 4, 62);
insert into place (name, type_id, location_id) values ('Gangdong', 3, 97);
insert into place (name, type_id, location_id) values ('Kalimati', 2, 140);
insert into place (name, type_id, location_id) values ('Makuyuni', 3, 103);
insert into place (name, type_id, location_id) values ('Krajan', 4, 54);
insert into place (name, type_id, location_id) values ('Arras', 3, 48);
insert into place (name, type_id, location_id) values ('Maluko', 4, 77);
insert into place (name, type_id, location_id) values ('Yangchao', 2, 108);
insert into place (name, type_id, location_id) values ('Davao', 4, 138);
insert into place (name, type_id, location_id) values ('Paris 18', 1, 131);
insert into place (name, type_id, location_id) values ('Kaiyuan', 4, 145);
insert into place (name, type_id, location_id) values ('Ma‘arrat an Nu‘mān', 1, 110);
insert into place (name, type_id, location_id) values ('San Ignacio de Tupile', 1, 98);
insert into place (name, type_id, location_id) values ('Strömsund', 4, 104);
insert into place (name, type_id, location_id) values ('Skidal’', 4, 69);
insert into place (name, type_id, location_id) values ('Tūkrah', 1, 98);
insert into place (name, type_id, location_id) values ('Tsiroanomandidy', 4, 66);
insert into place (name, type_id, location_id) values ('Del Campillo', 4, 123);
insert into place (name, type_id, location_id) values ('Strasbourg', 3, 111);
insert into place (name, type_id, location_id) values ('Wa', 1, 85);
insert into place (name, type_id, location_id) values ('Vila Flor', 2, 61);
insert into place (name, type_id, location_id) values ('Montgomery', 2, 133);
insert into place (name, type_id, location_id) values ('Kutapanjang', 3, 54);
insert into place (name, type_id, location_id) values ('Choros', 3, 77);
insert into place (name, type_id, location_id) values ('Aţ Ţaybah', 4, 45);
insert into place (name, type_id, location_id) values ('Tuguanpu', 2, 123);
insert into place (name, type_id, location_id) values ('T’aebaek', 1, 124);
insert into place (name, type_id, location_id) values ('Khoa', 4, 72);
insert into place (name, type_id, location_id) values ('Las Vegas', 2, 85);
insert into place (name, type_id, location_id) values ('Veranópolis', 4, 133);
insert into place (name, type_id, location_id) values ('Boa Esperança', 2, 63);
insert into place (name, type_id, location_id) values ('Kronshtadt', 4, 121);
insert into place (name, type_id, location_id) values ('Uppsala', 1, 40);
insert into place (name, type_id, location_id) values ('Umeå', 2, 85);
insert into place (name, type_id, location_id) values ('Al Ḩawāmidīyah', 3, 83);
insert into place (name, type_id, location_id) values ('San Vicente', 4, 60);
insert into place (name, type_id, location_id) values ('Songhe', 4, 43);
insert into place (name, type_id, location_id) values ('Menlou', 1, 62);
insert into place (name, type_id, location_id) values ('Pyetrykaw', 1, 105);
insert into place (name, type_id, location_id) values ('Ishigaki', 1, 60);
insert into place (name, type_id, location_id) values ('Pokrovskoye', 3, 56);
insert into place (name, type_id, location_id) values ('Herāt', 1, 54);
insert into place (name, type_id, location_id) values ('Songbai', 1, 78);
insert into place (name, type_id, location_id) values ('Lukolela', 4, 75);
insert into place (name, type_id, location_id) values ('Shaba', 4, 146);
insert into place (name, type_id, location_id) values ('Lufang', 2, 63);
insert into place (name, type_id, location_id) values ('Murcia', 2, 112);
insert into place (name, type_id, location_id) values ('Ekenäs', 1, 89);
insert into place (name, type_id, location_id) values ('San Francisco', 1, 41);
insert into place (name, type_id, location_id) values ('Périgueux', 2, 107);
insert into place (name, type_id, location_id) values ('Qizili', 4, 90);
insert into place (name, type_id, location_id) values ('Kołbiel', 4, 90);
insert into place (name, type_id, location_id) values ('Shuyuan Zhen', 2, 123);
insert into place (name, type_id, location_id) values ('Gennevilliers', 1, 122);
insert into place (name, type_id, location_id) values ('Gia Nghĩa', 4, 105);
insert into place (name, type_id, location_id) values ('Chorotis', 2, 49);
insert into place (name, type_id, location_id) values ('Sokyryany', 2, 111);
insert into place (name, type_id, location_id) values ('Biritiba Mirim', 4, 117);
insert into place (name, type_id, location_id) values ('Laguna', 4, 87);
insert into place (name, type_id, location_id) values ('São Gabriel', 2, 107);
insert into place (name, type_id, location_id) values ('Pilawa', 1, 46);
insert into place (name, type_id, location_id) values ('Driyorejo', 3, 46);
insert into place (name, type_id, location_id) values ('Osilnica', 3, 41);
insert into place (name, type_id, location_id) values ('Soure', 3, 128);
insert into place (name, type_id, location_id) values ('Chernyshevsk', 4, 144);
insert into place (name, type_id, location_id) values ('Ferreiros', 1, 60);
insert into place (name, type_id, location_id) values ('Mrozy', 3, 97);
insert into place (name, type_id, location_id) values ('Luoqiao', 3, 86);
insert into place (name, type_id, location_id) values ('Kolor', 3, 109);
insert into place (name, type_id, location_id) values ('Osieck', 2, 144);
insert into place (name, type_id, location_id) values ('Xiaojia', 4, 130);
insert into place (name, type_id, location_id) values ('Lucun', 4, 123);
insert into place (name, type_id, location_id) values ('Langley', 1, 74);
insert into place (name, type_id, location_id) values ('Totora', 1, 133);
insert into place (name, type_id, location_id) values ('Matoupu', 1, 41);
insert into place (name, type_id, location_id) values ('Jami', 2, 53);
insert into place (name, type_id, location_id) values ('Komaki', 2, 98);
insert into place (name, type_id, location_id) values ('Ngawen', 4, 64);
insert into place (name, type_id, location_id) values ('Azurva', 2, 114);
insert into place (name, type_id, location_id) values ('Kista', 2, 85);
insert into place (name, type_id, location_id) values ('Delft', 2, 48);
insert into place (name, type_id, location_id) values ('Charleston', 2, 103);
insert into place (name, type_id, location_id) values ('Dal’nerechensk', 4, 114);
insert into place (name, type_id, location_id) values ('Viga', 3, 110);
insert into place (name, type_id, location_id) values ('Ilanskiy', 4, 144);
insert into place (name, type_id, location_id) values ('Qingkenpao', 1, 134);
insert into place (name, type_id, location_id) values ('Shuangpu', 4, 90);
insert into place (name, type_id, location_id) values ('Töysä', 3, 123);
insert into place (name, type_id, location_id) values ('Sufang', 2, 121);
insert into place (name, type_id, location_id) values ('Rodionovo-Nesvetayskaya', 1, 73);
insert into place (name, type_id, location_id) values ('Sagang', 2, 92);
insert into place (name, type_id, location_id) values ('Maoshan', 4, 104);
insert into place (name, type_id, location_id) values ('Si Ma Cai', 3, 66);
insert into place (name, type_id, location_id) values ('Shibīn al Qanāţir', 3, 84);
insert into place (name, type_id, location_id) values ('Hutou', 1, 72);
insert into place (name, type_id, location_id) values ('Lesnyye Polyany', 2, 95);
insert into place (name, type_id, location_id) values ('Rūdiškės', 4, 83);
insert into place (name, type_id, location_id) values ('Gualeguay', 2, 138);
insert into place (name, type_id, location_id) values ('Bacolod', 3, 40);
insert into place (name, type_id, location_id) values ('Woshui', 3, 63);
insert into place (name, type_id, location_id) values ('Sungaikakap', 2, 85);
insert into place (name, type_id, location_id) values ('Xiashitai', 2, 103);
insert into place (name, type_id, location_id) values ('Dubrovka', 4, 69);
insert into place (name, type_id, location_id) values ('Pionerskiy', 4, 139);
insert into place (name, type_id, location_id) values ('Kuanfatu', 4, 100);
insert into place (name, type_id, location_id) values ('Tenjolaya', 2, 61);
insert into place (name, type_id, location_id) values ('Guaitarilla', 4, 126);
insert into place (name, type_id, location_id) values ('Dawuhan', 4, 77);
insert into place (name, type_id, location_id) values ('Cosne-Cours-sur-Loire', 2, 119);
insert into place (name, type_id, location_id) values ('Fengle', 4, 86);
insert into place (name, type_id, location_id) values ('Syanno', 2, 123);
insert into place (name, type_id, location_id) values ('Sendafa', 1, 95);
insert into place (name, type_id, location_id) values ('Longhuashan', 3, 106);
insert into place (name, type_id, location_id) values ('La Purisima', 3, 41);
insert into place (name, type_id, location_id) values ('Lüjiabao', 4, 108);
insert into place (name, type_id, location_id) values ('Tsybli', 4, 117);
insert into place (name, type_id, location_id) values ('Olonets', 4, 108);
insert into place (name, type_id, location_id) values ('Saky', 1, 70);
insert into place (name, type_id, location_id) values ('Priekule', 3, 95);
insert into place (name, type_id, location_id) values ('Rymanów', 2, 69);
insert into place (name, type_id, location_id) values ('Moss', 4, 49);
insert into place (name, type_id, location_id) values ('Huaihua', 1, 144);
insert into place (name, type_id, location_id) values ('Yuxi', 1, 51);
insert into place (name, type_id, location_id) values ('Odrinhas', 1, 144);
insert into place (name, type_id, location_id) values ('Chacabuco', 4, 75);
insert into place (name, type_id, location_id) values ('Corumbá', 2, 135);
insert into place (name, type_id, location_id) values ('Dankama', 3, 144);
insert into place (name, type_id, location_id) values ('Chervone', 4, 123);
insert into place (name, type_id, location_id) values ('Brandýs nad Labem-Stará Boleslav', 1, 42);
insert into place (name, type_id, location_id) values ('Las Terrenas', 2, 59);
insert into place (name, type_id, location_id) values ('‘Izbat al Burj', 3, 104);
insert into place (name, type_id, location_id) values ('Orvault', 4, 133);
insert into place (name, type_id, location_id) values ('Levallois-Perret', 3, 64);
insert into place (name, type_id, location_id) values ('Grzmiąca', 4, 64);
insert into place (name, type_id, location_id) values ('Jermenovci', 1, 103);
insert into place (name, type_id, location_id) values ('Qingguang', 4, 94);
insert into place (name, type_id, location_id) values ('Baxiangshan', 3, 144);
insert into place (name, type_id, location_id) values ('Chongxing', 3, 95);
insert into place (name, type_id, location_id) values ('Usuki', 3, 108);
insert into place (name, type_id, location_id) values ('Zghartā', 3, 50);
insert into place (name, type_id, location_id) values ('Arevik', 1, 71);
insert into place (name, type_id, location_id) values ('Xibei', 2, 123);
insert into place (name, type_id, location_id) values ('Pajung', 3, 40);
insert into place (name, type_id, location_id) values ('Sandaogou', 4, 135);
insert into place (name, type_id, location_id) values ('Shuangshan', 4, 101);
insert into place (name, type_id, location_id) values ('Capinzal', 4, 122);
insert into place (name, type_id, location_id) values ('Pilar', 1, 121);
insert into place (name, type_id, location_id) values ('Lanjaghbyur', 3, 123);
insert into place (name, type_id, location_id) values ('Sennoy', 3, 120);
insert into place (name, type_id, location_id) values ('Dashuipo', 3, 69);
insert into place (name, type_id, location_id) values ('Al Buţayḩah', 3, 134);
insert into place (name, type_id, location_id) values ('Bajiao', 2, 130);
insert into place (name, type_id, location_id) values ('Laprida', 4, 132);
insert into place (name, type_id, location_id) values ('Étampes', 1, 91);
insert into place (name, type_id, location_id) values ('Balboa', 3, 133);
insert into place (name, type_id, location_id) values ('Miaoling', 4, 123);
insert into place (name, type_id, location_id) values ('Dyurtyuli', 3, 63);
insert into place (name, type_id, location_id) values ('Banjar Dauhpura', 1, 67);
insert into place (name, type_id, location_id) values ('Al Bāriqīyah', 2, 57);
insert into place (name, type_id, location_id) values ('Shiye', 4, 119);
insert into place (name, type_id, location_id) values ('Austin', 2, 123);
insert into place (name, type_id, location_id) values ('Sernovodsk', 1, 108);
insert into place (name, type_id, location_id) values ('Dorogobuzh', 1, 121);
insert into place (name, type_id, location_id) values ('Újezd', 1, 90);
insert into place (name, type_id, location_id) values ('Sanski Most', 1, 143);
insert into place (name, type_id, location_id) values ('Villefranche-sur-Mer', 2, 136);
insert into place (name, type_id, location_id) values ('Or Yehuda', 2, 123);
insert into place (name, type_id, location_id) values ('New Orleans', 1, 123;